#!/bin/bash
# Run this script to intall scalegateway to run a startup
# and output to /var/log/syslog
echo installing scalegateway.service
sudo cp scalegateway.service /etc/systemd/system/
sudo systemctl enable scalegateway.service
